### ISSUE TITLE
bug with climatisation and vwsfriend stopped recording

### ISSUE THREAD

**Issue by daniel-w00** [tillsteinbach/VWsFriend#279] opened 2022-07-19 15:59 UTC
a bug occured (i believe something with climatisation, that was startet at 11:30). After that vwsfriend stopped recording. So probably related to #268. Restarting the container solves that

2022-07-19T11:11:41+0000:INFO:vwsfriend_base:Updating data from WeConnect
2022-07-19T11:16:41+0000:INFO:vwsfriend_base:Updating data from WeConnect
2022-07-19T11:21:41+0000:INFO:vwsfriend_base:Updating data from WeConnect
2022-07-19T11:21:43+0000:INFO:state_agent:Vehicle WVWZZZE1ZNP** went offline
2022-07-19T11:26:41+0000:INFO:vwsfriend_base:Updating data from WeConnect
2022-07-19T11:26:43+0000:INFO:state_agent:Vehicle WVWZZZE1ZNP** went online
2022-07-19T11:31:41+0000:INFO:vwsfriend_base:Updating data from WeConnect
2022-07-19T11:31:42+0000:WARNING:addressable:/vehicles/WVWZZZE1ZNP**/domains/automation/climatisationTimer/request/e5487263-c8e9-4e99-a180-372b706912fb/operation: An unsupported operation: timers was provided, known values are [start, stop, none, settings, unknown] please report this as a bug
2022-07-19T11:36:41+0000:INFO:vwsfriend_base:Updating data from WeConnect
2022-07-19T11:36:41+0000:INFO:openid_session:Token expired
2022-07-19T11:36:41+0000:INFO:we_connect_session:Refreshing tokens
2022-07-19T11:36:42+0000:WARNING:addressable:/vehicles/WVWZZZE1ZNP**/domains/automation/climatisationTimer/request/4f90f990-53c1-49b8-823c-08bef07a0919/operation: An unsupported operation: timers was provided, known values are [start, stop, none, settings, unknown] please report this as a bug
2022-07-19T11:41:41+0000:INFO:vwsfriend_base:Updating data from WeConnect
2022-07-19T11:41:42+0000:WARNING:addressable:/vehicles/WVWZZZE1ZNP**/domains/automation/climatisationTimer/request/4f90f990-53c1-49b8-823c-08bef07a0919/operation: An unsupported operation: timers was provided, known values are [start, stop, none, settings, unknown] please report this as a bug
Traceback (most recent call last):
  File "/opt/venv/bin/vwsfriend", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.9/site-packages/vwsfriend/vwsfriend_base.py", line 282, in main
    weConnect.update(updateCapabilities=True, updatePictures=True, force=True)
  File "/opt/venv/lib/python3.9/site-packages/weconnect/weconnect.py", line 177, in update
    self.updateComplete()
  File "/opt/venv/lib/python3.9/site-packages/weconnect/addressable.py", line 518, in updateComplete
    child.updateComplete()
  File "/opt/venv/lib/python3.9/site-packages/weconnect/addressable.py", line 518, in updateComplete
    child.updateComplete()
  File "/opt/venv/lib/python3.9/site-packages/weconnect/addressable.py", line 518, in updateComplete
    child.updateComplete()
  [Previous line repeated 3 more times]
  File "/opt/venv/lib/python3.9/site-packages/weconnect/addressable.py", line 96, in updateComplete
    observer(element=self, flags=self.onCompleteNotifyFlags)
  File "/opt/venv/lib/python3.9/site-packages/vwsfriend/agents/trip_agent.py", line 282, in __onPlugConnectionStateChanged
    if self.vehicle.weConnectVehicle.domains['readiness']['readinessStatus'].connectionState.isActive.value:
AttributeError: 'NoneType' object has no attribute 'isActive'

**Comment by tillsteinbach** [comment] 2022-07-24 08:48
This is a confirmed bug due to the readinessStatus being removed on VW side. Will be fixed with the next release.

**Comment by tillsteinbach** [comment] 2022-07-25 11:33
Fixed in 0.20.0

**Closed by tillsteinbach** 2022-07-25 11:33 UTC
Labels: bug
